package pt.ipp.estg.trabalho_cmu.data.models

/**
 * Represents a simplified model for an adoption request.
 *
 * This data class is likely used for communication with a remote data source like Firebase,
 * holding the essential information needed to identify a request, the user, the animal,
 * and its current status.
 *
 * @property id The unique identifier for the adoption request, typically generated by the remote database.
 * @property nome The name of the person submitting the request. (Portuguese for "name").
 * @property email The email address of the person submitting the request.
 * @property animal A reference to the animal being requested, which could be its name or ID.
 * @property status The current status of the adoption request (e.g., "PENDING"). Defaults to "PENDING".
 */
data class AdoptionRequest(
    val id: String = "",
    val nome: String = "",
    val email: String = "",
    val animal: String = "",
    val status: String = "PENDING"
)
