package pt.ipp.estg.trabalho_cmu.data.local.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import java.util.Date

/**
 * Represents a single record in the `activities` table of the local database.
 *
 * This data class models a scheduled activity, such as walking a dog, which involves
 * a specific user and a specific animal. It includes details about the pickup and
 * delivery times.
 *
 * @property id The unique identifier for the activity, auto-generated by the database.
 * @property userId The ID of the user who scheduled the activity. This acts as a foreign key to the `users` table.
 * @property animalId The ID of the animal involved in the activity. This acts as a foreign key to the `animals` table.
 * @property pickupDate The date when the activity starts, in string format (e.g., "YYYY-MM-DD").
 * @property pickupTime The time when the activity starts, in string format (e.g., "HH:MM").
 * @property deliveryDate The date when the activity ends, in string format (e.g., "YYYY-MM-DD").
 * @property deliveryTime The time when the activity ends, in string format (e.g., "HH:MM").
 * @property createdAt The timestamp (in milliseconds) when this activity record was created. Defaults to the current time.
 */
@Entity(
    tableName = "activities",
    /*foreignKeys = [
        ForeignKey(
            entity = Animal::class,
            parentColumns = ["id"],
            childColumns = ["animalId"],
            onDelete = ForeignKey.CASCADE // se o animal for apagado, apaga as atividades associadas
        )
    ]*/
)
data class Activity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    val userId: Int,
    val animalId: Int,

    val pickupDate: String,
    val pickupTime: String,
    val deliveryDate: String,
    val deliveryTime: String,

    val createdAt: Long = System.currentTimeMillis()
)
