package pt.ipp.estg.trabalho_cmu.data.local.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import pt.ipp.estg.trabalho_cmu.data.models.enums.AnimalStatus

/**
 * Represents a single animal in the `animals` table of the database.
 *
 * This data class defines the structure for an animal's record, including its
 * personal details, shelter information, and current status. It is linked to the
 * [Shelter] entity via a foreign key.
 *
 * @property id The unique identifier for the animal, auto-generated by the database.
 * @property name The name of the animal.
 * @property breed The breed of the animal (e.g., "Golden Retriever", "Siamese").
 * @property species The species of the animal (e.g., "Dog", "Cat").
 * @property size The size category of the animal (e.g., "Small", "Medium", "Large").
 * @property birthDate The date of birth of the animal, stored in string format (e.g., "YYYY-MM-DD").
 * @property imageUrls A list of URLs pointing to images of the animal. This list is converted to a storable format by a TypeConverter.
 * @property description A short text describing the animal's personality, history, or needs.
 * @property shelterId The ID of the [Shelter] where the animal is located. This is a foreign key.
 * @property status The current status of the animal (e.g., AVAILABLE, ADOPTED). Defaults to [AnimalStatus.AVAILABLE].
 * @property createdAt The timestamp (in milliseconds) when the animal's record was created. Defaults to the current time.
 */
@Entity(
    tableName = "animals",
    foreignKeys = [
        ForeignKey(
            entity = Shelter::class,
            parentColumns = ["id"],
            childColumns = ["shelterId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index(value = ["shelterId"])]
)
data class Animal(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val name: String,
    val breed: String,
    val species: String,
    val size: String,
    val birthDate: String,
    val imageUrls: List<String>,
    val description:String,
    val shelterId: Int,
    val status: AnimalStatus = AnimalStatus.AVAILABLE,
    val createdAt: Long = System.currentTimeMillis()
)
