package pt.ipp.estg.trabalho_cmu.data.local.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import pt.ipp.estg.trabalho_cmu.data.models.enums.OwnershipStatus

/**
 * Represents an ownership (or "special adoption") request in the `OwnershipRequests` table.
 *
 * This entity links a [User], an [Animal], and a [Shelter] together for an adoption process.
 * It stores payment details required for the request and tracks its lifecycle through a status
 * field (e.g., PENDING, APPROVED, REJECTED).
 *
 * @property id The unique identifier for the ownership request, auto-generated by the database.
 * @property userId The ID of the [User] submitting the request. Acts as a foreign key to the `users` table.
 * @property animalId The ID of the [Animal] being requested for adoption. Acts as a foreign key to the `animals` table.
 * @property shelterId The ID of the [Shelter] that holds the animal. Acts as a foreign key to the `shelters` table.
 * @property ownerName The full name of the person submitting the request.
 * @property accountNumber The bank account number for payment purposes.
 * @property cvv The Card Verification Value (CVV) for the payment card.
 * @property cardNumber The payment card number.
 * @property status The current status of the ownership request. Defaults to [OwnershipStatus.PENDING].
 * @property createdAt The timestamp (in milliseconds) when the request was created. Defaults to the current time.
 */
@Entity(
    tableName = "OwnershipRequests"
,
    foreignKeys = [
        ForeignKey(
            entity = User::class,
            parentColumns = ["id"],
            childColumns = ["userId"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = Animal::class,
            parentColumns = ["id"],
            childColumns = ["animalId"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = Shelter::class,
            parentColumns = ["id"],
            childColumns = ["shelterId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [
        Index(value = ["userId"]),
        Index(value = ["animalId"]),
        Index(value = ["shelterId"])
    ]
)
data class Ownership(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    // Foreign Keys
    val userId: Int,
    val animalId: Int,
    val shelterId: Int,

    // Payment and identification info
    val ownerName: String,
    val accountNumber: String,
    val cvv: String,
    val cardNumber: String,

    // Ownership status
    @ColumnInfo(defaultValue = "PENDING")
    val status: OwnershipStatus = OwnershipStatus.PENDING,

    val createdAt: Long = System.currentTimeMillis()
)