package pt.ipp.estg.trabalho_cmu.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents an animal shelter in the `shelters` table of the database.
 *
 * This data class models the essential information about a shelter, including
 * its contact details and an optional link to a Firebase user account.
 *
 * @property id The unique identifier for the shelter, auto-generated by the database.
 * @property firebaseUid The unique ID from Firebase Authentication, used to link this local record
 *           to a remote user account. It is nullable for shelters that may not be linked.
 * @property name The official name of the shelter.
 * @property address The physical address of the shelter.
 * @property phone The contact phone number for the shelter.
 * @property email The contact email address for the shelter.
 * @property password The password associated with the shelter's account.
 *           Note: Storing plain-text passwords is not secure. This should ideally be a hashed value.
 */
@Entity(tableName = "shelters")
data class Shelter(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val firebaseUid: String? = null,
    val name: String,
    val address: String,
    val phone: String,
    val email: String,
    val password: String
)
