package pt.ipp.estg.trabalho_cmu.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user in the `users` table of the database.
 *
 * This data class models the essential information for a user account,
 * including personal details, contact information, and credentials. It can
 * optionally be linked to a Firebase account.
 *
 * @property id The unique identifier for the user, auto-generated by the database.
 * @property firebaseUid The unique ID from Firebase Authentication, which links this
 *           local user record to a remote Firebase account. It is nullable.
 * @property name The full name of the user.
 * @property adress The physical address of the user. (Note: "adress" is likely a typo for "address").
 * @property email The user's email address, used for login and communication.
 * @property phone The user's contact phone number.
 * @property password The password for the user's account.
 *           Note: Storing passwords in plain text is insecure. It is highly
 *           recommended to store a hashed version of the password instead.
 */
@Entity(tableName = "users")
data class User(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val firebaseUid: String? = null,
    val name: String,
    val adress: String,
    val email: String,
    val phone: String,
    val password: String
)
